# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_SIRTGP_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_SIRTGP_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_SIRTGP_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_SIRTGP_rcpparma_bothproducts`, x)
}

sample_cpp <- function(x, size, replace, prob) {
    .Call(`_SIRTGP_sample_cpp`, x, size, replace, prob)
}

quantile_cpp <- function(x, size, low, high) {
    .Call(`_SIRTGP_quantile_cpp`, x, size, low, high)
}

rtrunc_Rpkg <- function(a, b, mu, sd) {
    .Call(`_SIRTGP_rtrunc_Rpkg`, a, b, mu, sd)
}

fun_mul <- function(A, x) {
    .Call(`_SIRTGP_fun_mul`, A, x)
}

fun_dev <- function(A, x) {
    .Call(`_SIRTGP_fun_dev`, A, x)
}

G_thres_cpp <- function(x, thres) {
    .Call(`_SIRTGP_G_thres_cpp`, x, thres)
}

sample_e_cpp <- function(k, l, K, rt, Z, X, Xmat, SR_other, S0, E_hat, thres1, lambda, tausq) {
    .Call(`_SIRTGP_sample_e_cpp`, k, l, K, rt, Z, X, Xmat, SR_other, S0, E_hat, thres1, lambda, tausq)
}

sample_ic_cpp <- function(n, Z, SR_other, S0, tausq) {
    .Call(`_SIRTGP_sample_ic_cpp`, n, Z, SR_other, S0, tausq)
}

sample_eta_cpp <- function(u, v, K, rt, Z, X, X0, SR, S0_other, E_hat, eta_hat, thres1, thres2, tausq, sigsq_eta) {
    .Call(`_SIRTGP_sample_eta_cpp`, u, v, K, rt, Z, X, X0, SR, S0_other, E_hat, eta_hat, thres1, thres2, tausq, sigsq_eta)
}

sample_E_hat_cpp <- function(k, j, K, rt, Z, X, Xmat, SR_other, S0, e, eta_m, thres1, tausq, sigsq) {
    .Call(`_SIRTGP_sample_E_hat_cpp`, k, j, K, rt, Z, X, Xmat, SR_other, S0, e, eta_m, thres1, tausq, sigsq)
}

sample_eta_hat_cpp <- function(u, v, K, rt, Z, X, X0, Xmat, SR, S0_other, eta, thres2, tausq, sigsq) {
    .Call(`_SIRTGP_sample_eta_hat_cpp`, u, v, K, rt, Z, X, X0, Xmat, SR, S0_other, eta, thres2, tausq, sigsq)
}

loglike_cpp <- function(n, Y, SR, S0, tausq) {
    .Call(`_SIRTGP_loglike_cpp`, n, Y, SR, S0, tausq)
}

sample_Z <- function(n, Y, SR, S0) {
    .Call(`_SIRTGP_sample_Z`, n, Y, SR, S0)
}

sample_thres1 <- function(n, K, Z, X, Xmat, val, prob1, eta_m, e, E_hat, S0, tausq, rt) {
    .Call(`_SIRTGP_sample_thres1`, n, K, Z, X, Xmat, val, prob1, eta_m, e, E_hat, S0, tausq, rt)
}

sample_thres2 <- function(n, K, Z, X0, val, prob2, eta, eta_hat, SR, tausq) {
    .Call(`_SIRTGP_sample_thres2`, n, K, Z, X0, val, prob2, eta, eta_hat, SR, tausq)
}

SIRTGP_fit <- function(T, K, L, n, Y, X, X0, Xmat, eta, eta_m, e, E_hat, eta_hat, beta0, thres1, thres2, lambda, tausq, sigsq, sigsq_eta, rt, alpha1, alpha2, prob1, prob2, val1, val2) {
    .Call(`_SIRTGP_SIRTGP_fit`, T, K, L, n, Y, X, X0, Xmat, eta, eta_m, e, E_hat, eta_hat, beta0, thres1, thres2, lambda, tausq, sigsq, sigsq_eta, rt, alpha1, alpha2, prob1, prob2, val1, val2)
}

